accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('c_signup/', views.c_signup, name='c_signup'),
    path('p_signup/', views.p_signup, name='p_signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout,  name='logout'),    
    path('c_update/',views.c_update, name='c_update'),
    path('p_update/',views.p_update, name='p_update'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main, name = 'main'),
    path('new_performance/', views.new_performance, name = 'new_performance'),
    path('performance/<int:index>',views.performance, name='performance'),
    path('comment_delete/<int:comment_id>',views.comment_delete,name='comment_delete'),
    path('pay/<int:index>',views.pay, name='pay'),
    path('complete/',views.complete, name='complete'),
    path('p_detail/<int:index>',views.p_detail, name='p_detail'),
    path('c_mypage/',views.c_mypage, name='c_mypage'),
    path('p_mypage/',views.p_mypage, name='p_mypage'),
    # path('performance/<pk>/likes/', views.like, name='likes'),
    path('performance/<int:pk>/like', views.like, name = 'like'),
    path('search/',views.search, name='search'),
]

gazami/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts import views as user_views
from django.contrib.auth import views as auth_views
import blog.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', blog.views.main, name='main'),
]
urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from blog import models as mo

class CUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    check = models.BooleanField(default = True)
    c_phone = models.CharField(max_length=11, default="")
    post = models.ForeignKey(mo.Post , on_delete=models.CASCADE, null=True, blank=True)

class PUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    check = models.BooleanField(default = False)
    p_phone = models.CharField(max_length=11, default="")
   # p_image = forms.ImageField()
   # p_information = forms.CharField(widget=forms.Textarea)
    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import models
from .models import CUser


class c_RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', #ID 
        'first_name', #이름
        'email', 'password1', 'password2'
        ]

        
class cuserForm(forms.ModelForm):
    class Meta:
        model = CUser
        fields = ['check',]

class p_RegisterForm(UserCreationForm):
    p_name = forms.CharField()
    p_email = forms.EmailField()
    p_phone = forms.CharField()
   # p_image = forms.ImageField()
   # p_information = forms.CharField(widget=forms.Textarea)
    
    class Meta:
        model = User
        fields = ['p_name', 'username', 'password1', 'password2',
        'p_phone', 'p_email', 
        #'p_image', 'p_information',
        ]

class c_updateForm(UserChangeForm):
    c_name = forms.CharField()
    c_email = forms.EmailField()
    c_phone = forms.CharField()

    class Meta:
        model = User
        fields = ['c_name', 'c_phone', 'c_email', 
        # 'c_image',
        ]

class p_updateForm(UserChangeForm):
    p_name = forms.CharField()
    p_email = forms.EmailField()
    p_phone = forms.CharField()
   # p_image = forms.ImageField()
   # p_information = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = User
        fields = ['p_name', 'p_phone', 'p_email', 
        #'p_image', 'p_information',
        ]

accounts/views.py
from django.shortcuts import render, redirect
from .forms import c_RegisterForm, p_RegisterForm, c_updateForm, p_updateForm, cuserForm
from django.contrib import auth
from django.contrib.auth.models import User
from .models import CUser, PUser
# Create your views here.

def c_signup(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"],
                email=request.POST["email"],
                first_name=request.POST["first_name"],
                )
            cuser = CUser(
                user=user,
                c_phone=request.POST["c_phone"],
                )
            cuser.save()
            auth.login(request,user)
            return redirect('main')
    return render(request, 'accounts/c_signup.html')

def p_signup(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"],
                email=request.POST["email"],
                first_name=request.POST["first_name"],
                )
            puser = PUser(
                user=user,
                p_phone=request.POST["p_phone"],
                )
            puser.save()
            auth.login(request,user)
            return redirect('main')
    return render(request, 'accounts/p_signup.html')
            
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        user = auth.authenticate(request, username = username, password = password)

        if user is not None:
            auth.login(request, user)
            return redirect('main')
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')       

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('main')
    return redirect('login')

def c_update(request): #예매자 회원 회원정보 수정
    if request.method == 'POST':
        form = c_updateForm(data=request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
    else:
        form = c_updateForm(instance=request.user)
    return render(request, 'accounts/c_update.html',{'form':form})

def p_update(request): #공연자 회원 회원정보 수정
    if request.method == 'POST':
        form = p_updateForm(data=request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
    else:
        form = p_updateForm(instance=request.user)
    return render(request, 'accounts/p_update.html',{'form':form})

templates/accounts/c_mypage.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
    {% load staticfiles%}
        <div class='upper_blank_main'></div>

        <br>
        {% if user.is_authenticated %}
        {% if user.cuser.check %}
            <!-- 프로필 이미지가 들어가야 한다 -->
            <div class='profile-container'>
                <div class='profile-cropper'>
                    <img class='profile-img' src="{% static 'images/default_profile.png' %}" alt="">
                </div>
                <br>
                <h3 class='hanna'>{{ request.user.username }}</h3>
                <a class='esup modify' href="{% url 'c_update' %}">회원정보수정</a>
                <span>|</span>
                <a class="esup" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
                <form id="logout" method="POST" action="{% url 'logout' %}">
                {% csrf_token %} <input type="hidden">
            </div>

    <div class='container'>
        <br>
        <h3 class='esup now-performing'>"{{user.username}}"님이<br>예매한 공연</h3>
        <br>
        
        <br>
        <h3>내가 예매한 공연</h3>
        {% for ticket in tickets_list %}
            {% if ticket.author == user %}
            공연명 : <a href="{% url 'performance' index=ticket.post.pk %}">{{ticket.post.show_title}}</a><br>
            예매 매수: {{ ticket.count }}
            <br>
            {% endif %}
        {% endfor %}


            <br>
            <h3 class='esup now-performing'>지난 예매한 공연</h3>
            <br>
            {% for post in posts_list %}
            {% if post.post_author == user %}
                {% if post.show_poster %}
                        <div class="card" style="width: 18rem;">
                                <img src="{{post.show_poster.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                                <p class="card-text esup">{{post.post_author}}</p>
                                <a class='btn btn-warning esup' href="{% url 'performance' index=post.pk %}">자세히 보기</a>
                            </div>
                        </div>
                        <br>
                {% else %}
                    <div class="card" style="width: 18rem;">
                        <div class='no-poster-card'>
                            <img src="{% static 'images/no_poster.png' %}" class="card-img-top" alt="...">
                            <p class='esup font-purple'>지금 내 기분이 그래<br>포스터가 없넹..?</p>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                            <p class="card-text esup">{{post.post_author}}</p>
                            <a class='btn btn-warning esup' href="{% url 'performance' index=post.pk %}">자세히 보기</a>
                        </div>
                    </div>
                    <br>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% else %}
        <br>
        <br>
        <br>
        <div class='profile-container'>
            <h4 class='esup'>예매자 회원만 이용 가능한 서비스입니다!</h4>
            <br>
            <a href= "{% url 'main' %}"><img class='btn_login_mypage' src="{% static 'images/btn_confirm.png' alt='btn upload fail' %}"></a>
        </div>
        {% endif %}


        {% else %}
        <br>
        <br>
        <br>
        <div class='profile-container'>
            <h4 class='esup'>로그인이 필요한 서비스입니다!</h4>
            <br>
            <a href= "{% url 'login' %}"><img class='btn_login_mypage' src="{% static 'images/btn_login.png' alt='btn upload fail' %}"></a>
        </div>
        

        {% endif %}
    </div>

{% endblock %}

templates/accounts/c_signup.html
{% extends 'base/navbar.html' %}


{% block content %}
    {% load staticfiles %}
        <div class='container'>
        <div class='upper_blank'></div><div class='upper_blank'></div>
        <div class='upper_blank'></div>
        <h1 class = 'register esup h1_signup'>예매자 회원가입</h2>
    <form method="POST" action="{% url 'c_signup' %}">
        {% csrf_token %}
        <p>
            <div class="form-group">
                <label for="id_username" class='esup'>아이디: <span class="required">*</span></label> 
                <input type="text" name="username" class="form-control username" id="id_username" aria-describedby="emailHelp" 
                placeholder="likelion123" required>
            </div>
        </p>
        <p>
            <div class="form-group">
                <label for="id_password1" class='esup'>비밀번호: <span class="required">*</span></label>
                <input type="password" class="form-control" id="id_passsword1" name = "password1" placeholder="비밀번호 입력" required>
            </div>
        </p>        
        <p>
            <div class="form-group">
                <label for="id_password2" class='esup'>비밀번호 확인: <span class="required">*</span></label>
                <input type="password" class="form-control" id="id_passsword2" name = "password2" placeholder="비밀번호 입력" required>
                <small id="passwordHelp" class="form-text text-muted helptext esup">확인을 위해 이전과 동일한 비밀번호를 입력하세요. </small>
            </div>
        </p>       
        <br>
        <p>
            <div class="form-group">
                <label for="id_first_name" class='esup'>사용자 이름: <span class="required">*</span></label> 
                <input type="text" class="form-control" id="id_first_name" aria-describedby="emailHelp" placeholder="홍길동"
                maxlength = "150" name="first_name" required>
                <small id="nameHelp" class="form-text text-muted helptext esup">정확한 이름을 입력하세요.</small>
            </div>
        </p>   

        <p>
            <div class="form-group">
                <label for="id_c_phone" class='esup'>핸드폰 번호: <span class="required">*</span></label> 
                <input type="text" class="form-control username" id="id_c_phone" aria-describedby="emailHelp" placeholder="01012345678"
                maxlength = "150" name = "c_phone" required>
                <small id="nameHelp" class="form-text text-muted helptext esup">대쉬(-) 없이 숫자만 입력하세요.</small>
            </div>
        </p>

            <div class="form-group">
                <label for="id_email" class='esup'>이메일 주소: <span class="required">*</span></label>
                <input type="email" name="email" class="form-control" id="id_email" placeholder="name@example.com" required>
            </div>
        </p>
        <div class='btn_container'>
            <button class='register_button' type="submit">
                <img class='btn_register' src="{% static 'images/btn_register.jpeg' alt='btn upload fail' %}">
            </button>
        </div>
    </form>
    </div>
{% endblock %}

templates/accounts/login.html
<!DOCTYPE html>

{% extends 'base/navbar.html' %}

{% block content %}
    {% load staticfiles %}
    <html>
        <head>
            <link rel="stylesheet" href="{% static 'css/accounts_style.css' %}">
           <!-- <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
        </head>
        <body class="text-center">
            <form class="form-signin" method="POST" action="{% url 'login' %}">
                {% csrf_token %}
                <img src="{% static 'images/purple_gazami1.png' alt='btn upload fail' %}" width="22%">
                <h1 class="h1_login h3 mb-3 font-weight-normal">로그인</h1>
                <label for="inputId" class="sr-only"></label>
                <input name = "username" type="text" id="inputId" class="form-control" placeholder="Id" required="" autofocus=""><br/>
                <label for="inputPassword" class="sr-only"></label>
                <input name = "password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
                <div class='btn_container'>
                    <button class='login_button' type="submit" value="Login">
                        <img class='btn_login' src="{% static 'images/btn_login.png' alt='btn upload fail' %}">
                    </button>
                </div>
                <a href = "{% url 'c_signup' %}">예매자 회원가입</a><br>
                <a href = "{% url 'p_signup' %}">공연자 회원가입</a>
            </form>
        </body>
    {% endblock %}    
</html>

templates/accounts/p_mypage.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
    {% load staticfiles%}
        <div class='upper_blank_main'></div>

        <br>
        {% if user.is_authenticated %}
        {% if user.cuser.check %}
        <br>
        <br>
        <br>
        <div class='profile-container'>
            <h4 class='esup'>공연자 회원만 이용 가능한 서비스입니다!</h4>
            <br>
            <a href= "{% url 'main' %}"><img class='btn_login_mypage' src="{% static 'images/btn_confirm.png' alt='btn upload fail' %}"></a>
        </div>
        {% else %}


        
            <!-- 프로필 이미지가 들어가야 한다 -->
            <div class='profile-container'>
                <div class='profile-cropper'>
                    <img class='profile-img' src="{% static 'images/default_profile.png' %}" alt="">
                </div>
                <br>
                <h3 class='hanna'>{{ request.user.username }}</h3>
                <a class='esup modify' href="{% url 'p_update' %}">회원정보수정</a>
                <span>|</span>
                <a class="esup" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
                <form id="logout" method="POST" action="{% url 'logout' %}">
                {% csrf_token %} <input type="hidden">
            </div>

    <div class='container'>
        <br>
        <h3 class='esup now-performing'>"{{user.username}}"님의<br>공연중인 작품</h3>
        <br>
        {% for post in posts_list %}
            {% if post.post_author == user %}
                {% if post.show_poster %}
                        <div class="card">
                                <img src="{{post.show_poster.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                                <p class="card-text esup">{{post.post_author}}</p>
                                <a class='btn btn-warning esup' href="{% url 'p_detail' index=post.pk %}">자세히 보기</a>
                            </div>
                        </div>
                        <br>
                {% else %}
                    <div class="card" style="width: 18rem;">
                        <div class='no-poster-card'>
                            <img src="{% static 'images/no_poster.png' %}" class="card-img-top" alt="...">
                            <p class='esup font-purple'>지금 내 기분이 그래<br>포스터가 없넹..?</p>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                            <p class="card-text esup">{{post.post_author}}</p>
                            <a class='btn btn-warning esup' href="{% url 'p_detail' index=post.pk %}">자세히 보기</a>
                        </div>
                    </div>
                    <br>
                {% endif %}
            {% endif %}
        {% endfor %}
            <br>
            <a class='btn btn-warning esup' href="{% url 'new_performance' %}">+(공연 추가하기)</a>
            <br>
            <br>


            <br>
            <h3 class='esup now-performing'>지난 공연</h3>
            <br>
            {% for post in posts_list %}
            {% if post.post_author == user %}
                {% if post.show_poster %}
                        <div class="card" style="width: 18rem;">
                                <img src="{{post.show_poster.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                                <p class="card-text esup">{{post.post_author}}</p>
                                <a class='btn btn-warning esup' href="{% url 'performance' index=post.pk %}">자세히 보기</a>
                            </div>
                        </div>
                        <br>
                {% else %}
                    <div class="card" style="width: 18rem;">
                        <div class='no-poster-card'>
                            <img src="{% static 'images/no_poster.png' %}" class="card-img-top" alt="...">
                            <p class='esup font-purple'>지금 내 기분이 그래<br>포스터가 없넹..?</p>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title esup">"{{ post.show_title }}"</h5>
                            <p class="card-text esup">{{post.post_author}}</p>
                            <a class='btn btn-warning esup' href="{% url 'performance' index=post.pk %}">자세히 보기</a>
                        </div>
                    </div>
                    <br>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% endif %}


        {% else %}
        <br>
        <br>
        <br>
        <div class='profile-container'>
            <h4 class='esup'>로그인이 필요한 서비스입니다!</h4>
            <br>
            <a href= "{% url 'login' %}"><img class='btn_login_mypage' src="{% static 'images/btn_login.png' alt='btn upload fail' %}"></a>
        </div>

        {% endif %}
    </div>

{% endblock %}

templates/accounts/p_signup.html
{% extends 'base/navbar.html' %}


{% block content %}
    {% load staticfiles %}
        <div class='container'>
        <div class='upper_blank'></div><div class='upper_blank'></div>
        <div class='upper_blank'></div>
        <h1 class = 'register esup h1_signup'>공연자 회원가입</h1>
    <form method="POST" action="{% url 'p_signup' %}">
        {% csrf_token %}
        <p>
            <div class="form-group">
                <label for="id_username" class='esup'>아이디: <span class="required">*</span></label> 
                <input type="text" name="username" class="form-control username" id="id_username" aria-describedby="emailHelp" placeholder="likelion123" required>
            </div>
        </p>
        <p>
            <div class="form-group">
                <label for="id_password1" class='esup'>비밀번호: <span class="required">*</span></label>
                <input type="password" class="form-control" id="id_passsword1" name = "password1" placeholder="비밀번호 입력" required>
            </div>
        </p>
        <p>
            <div class="form-group">
                <label for="id_password2" class='esup'>비밀번호 확인: <span class="required">*</span></label>
                <input type="password" class="form-control" id="id_passsword2" name = "password2" placeholder="비밀번호 입력" required>
                <small id="passwordHelp" class="form-text text-muted helptext esup">확인을 위해 이전과 동일한 비밀번호를 입력하세요. </small>
            </div>
        </p>

        <br>

        <p>
            <div class="form-group">
                <label for="id_first_name" class='esup'>사용자 이름: <span class="required">*</span></label> 
                <input type="text" class="form-control" id="id_first_name" aria-describedby="emailHelp" placeholder="홍길동"
                maxlength = "150" name="first_name" required>
                <small id="nameHelp" class="form-text text-muted helptext esup">정확한 이름을 입력하세요.</small>
            </div>
        </p>
        <p>
            <div class="form-group">
                <label for="id_p_phone" class='esup'>핸드폰 번호: <span class="required">*</span></label> 
                <input type="text" class="form-control username" id="id_p_phone" aria-describedby="emailHelp" placeholder="01012345678"
                maxlength = "150" name = "p_phone" required>
                <small id="nameHelp" class="form-text text-muted helptext esup">대쉬(-) 없이 숫자만 입력하세요.</small>
            </div>
        </p>
        <p>
            <div class="form-group">
                <label for="id_email" class='esup'>이메일 주소: <span class="required">*</span></label>
                <input type="email" name="email" class="form-control" id="id_email" placeholder="name@example.com" required>
            </div>
        </p>
        <div class='btn_container'>
            <button class='register_button' type="submit">
                <img class='btn_register' src="{% static 'images/btn_register.jpeg' alt='btn upload fail' %}">
            </button>
        </div>
    </form>
    </div>
{% endblock %}