blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('main/', views.main, name = 'main'),
    path('new_performance/', views.new_performance, name = 'new_performance'),
    path('performance/<int:index>',views.performance, name='performance'),
    path('comment_delete/<int:comment_id>',views.comment_delete,name='comment_delete'),
    path('pay/<int:index>',views.pay, name='pay'),
    path('complete/',views.complete, name='complete'),
    path('p_detail/<int:index>',views.p_detail, name='p_detail'),
    path('c_mypage/',views.c_mypage, name='c_mypage'),
    path('p_mypage/',views.p_mypage, name='p_mypage'),
    # path('performance/<pk>/likes/', views.like, name='likes'),
    path('performance/<int:pk>/like', views.like, name = 'like'),
    path('search/',views.search, name='search'),
]

gazami/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts import views as user_views
from django.contrib.auth import views as auth_views
import blog.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', blog.views.main, name='main'),
]
urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from datetime import date, datetime
from django.conf import settings
from accounts import models as mo
# Create your models here.

class Post(models.Model):
    post_author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    show_title = models.CharField(default = '', max_length=200)
    show_poster = models.ImageField(upload_to='images/', blank=True)
    show_start_date = models.DateField(null=True, blank=True) #2019-07-31 이런식으로 적어야함 
    show_end_date = models.DateField(null=True, blank=True)
    show_time = models.TextField(default = '')
    show_place = models.TextField(default = '')
    ticket_date_1 = models.DateTimeField(null=True, blank=True)
    ticket_date_2 = models.DateTimeField(null=True, blank=True)
    ticket_date_3 = models.DateTimeField(null=True, blank=True)
    ticket_date_4 = models.DateTimeField(null=True, blank=True)
   # ticket_date_5 = models.DateTimeField(null=True, blank=True)

    # ticket_date = ArrayField(models.DateField(blank=True), default = list)
    # ticket_date = models.TextField(default = '')    
    ticket_price_1 = models.BigIntegerField(null=True, blank=True)
    ticket_price_2 = models.BigIntegerField(null=True, blank=True)
    #ticket_price_3 = models.BigIntegerField(default = '')
    ticket_price_3 = models.BigIntegerField(null=True, blank=True)
    ticket_price_4 = models.BigIntegerField(null=True, blank=True)
   # ticket_price_5 = models.BigIntegerField(default = '')
    #ticket_price_5 = models.BigIntegerField(default = '')
   # ticket_price_5 = models.BigIntegerField(default='')
    ticket_amount_1 = models.BigIntegerField(null=True, blank=True)
    ticket_amount_2 = models.BigIntegerField(null=True, blank=True)
    ticket_amount_3 = models.BigIntegerField(null=True, blank=True)
    ticket_amount_4 = models.BigIntegerField(null=True, blank=True)
   # ticket_amount_5 = models.BigIntegerField(default = '')

    
    bankname = models.CharField(default = '', max_length=200)
    account = models.BigIntegerField()
    opendate = models.DateField(null=True, blank=True)
    closedate = models.DateField(null=True, blank=True)
    canceldate = models.DateField(null=True, blank=True)
    show_info_text = models.TextField(default = '', null=True, blank=True)
    show_info_image = models.ImageField(upload_to='images/', blank=True)

    approve = models.BooleanField(default="False") #관리자승인용 False:미승인 True:승인
    # like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='like_user_set')
    
    # def like_count(self):
    #     return self.like_user_set.count()
    
class PostLike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    content = models.CharField(max_length=300)
    timestamp = models.DateTimeField(default=timezone.now)

class Ticket(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) #예매하는 공연정보
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) #예매자정보
    count = models.IntegerField(default = '1') #티켓 매수
    timestamp = models.DateTimeField(default=timezone.now)
    T1 = 'ticket1'
    T2 = 'ticket2'
    T3 = 'ticket3'
    T4 = 'ticket4'
    TICKET_CHOICES = [
        (T1, 'c1'),
        (T2, 'c2'),
        (T3, 'c3'),
        (T4, 'c4'),
    ]
    t_choice = models.CharField(
        max_length=100,
        choices=TICKET_CHOICES,
        default=T1,
    )

class CanceledTicket(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) #예매한 공연정보
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) #예매자정보
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE) #취소 티켓정보
    refund_bank = models.CharField(default = '', max_length=200) #환불계좌은행
    refund_account = models.BigIntegerField() #환불계좌번호

blog/forms.py
from django import forms
from .models import Post, Comment, Ticket

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['show_title', 
         'show_poster' , 'show_start_date', 'show_end_date',  'show_time', 'show_place', 
         'ticket_date_1', 'ticket_date_2', 'ticket_date_3', 'ticket_date_4', 
         #'ticket_date_5',
        'ticket_price_1', 
         'ticket_price_2' ,
   #      'ticket_price_3',
         'ticket_price_3',
         'ticket_price_4', 
    #     'ticket_price_5',
     #   'ticket_price_5',
     #   'ticket_price_5',
         'ticket_amount_1',   'ticket_amount_2',  'ticket_amount_3',  'ticket_amount_4',  
         #'ticket_amount_5',
         'bankname', 'account', 
         'opendate', 
         'closedate', 'canceldate', 
         'show_info_text', 'show_info_image', 
        ]
        


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['t_choice','count',]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Ticket, PostLike
from .forms import PostForm, CommentForm, TicketForm
from accounts.models import CUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

#Import for search
from django.views.generic.edit import FormView

from django.db.models import Q
from django.shortcuts import render

from datetime import date
# Create your views here.
def main(request):
    posts = Post.objects.all
    return render(request, 'blog/main.html', {'posts_list' : posts})

def performance(request, index): 
    post = get_object_or_404(Post, pk=index)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('performance',index)
    elif request.method == "GET":
        form = CommentForm()
        comments = Comment.objects.filter(post=post)
        return render(request, 'blog/performance.html', {'post':post, 'form':form, 'comments':comments})

def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = get_object_or_404(Post, pk=comment.post.pk)
    if request.user != comment.author:
        messages.warning(requset, '권한없음')
        return redirect('performance',index=comment.post.pk)
    else:
        return render(request, 'comment_delete',{'comment':comment})

def pay(request, index): #예매하기
    post = get_object_or_404(Post, pk=index)
    if request.method == 'POST':
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.author = request.user
            ticket.post = post
            ticket.save()
            return render(request, 'blog/complete.html',{'ticket':ticket, 'post':post})
    else:
        form = TicketForm()
    return render(request, 'blog/pay.html',{'form':form, 'post':post})

def complete(request):
    return render(request, 'blog/complete.html')

def new_performance(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_author = request.user
            post.save()
            return redirect('main')
    else:
        form = PostForm()
    
    return render(request, 'blog/new_performance.html', {'form': form})

def p_detail(request, index):
    post = get_object_or_404(Post, pk=index)
    tickets = Ticket.objects.all
    return render(request, 'blog/p_detail.html', {'post':post, 'tickets':tickets})

def c_mypage(request):
    posts = Post.objects.all
    tickets = Ticket.objects.all
    return render(request, 'accounts/c_mypage.html',{'posts_list' : posts, 'tickets_list' : tickets})

def p_mypage(request):
    posts = Post.objects.all
    return render(request, 'accounts/p_mypage.html',{'posts_list' : posts})

@login_required
def like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if PostLike.objects.filter(post=post, user=request.user).count() == 0:
        PostLike.objects.create(post=post, user=request.user)
    else : 
        instance = PostLike.objects.get(post=post, user=request.user)
        instance.delete()
    return redirect('performance', index=pk)

def search(request):
    template = 'blog/search.html'
    query = request.GET.get('q')
    results = Post.objects.all
    if query:
        results = Post.objects.filter(Q(show_title__icontains=query))
   
    return render(request, template, {'posts_list' : results})

    # Create your views here.

templates/blog/c_mypage.html
<h1>예매자 마이페이지</h1>

{% if user.is_authenticated %}
    <h3>반갑습니다. {{user.username}}님!</h3>
    <a href="{% url 'new_performance' %}">글쓰기</a>
    <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
    <form id="logout" method="POST" action="{% url 'logout' %}">
    {% csrf_token %} <input type="hidden">
{% else %}
    <a href= "{% url 'login' %}">로그인</a>
{% endif %}
<br>
<br>
<h3>현재예매작</h3>




<br>
<h3>지난공연</h3>

templates/blog/complete.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
{% load staticfiles %}

<br>
<br>
<br>
<br>
<br>

<div class='btn_container'>
    
    <h3 class='esup'>요청하신 예매가<br> 완료되었습니다!</h3>
    <br>
    <br>
    <h3 class='esup'>예매정보</h3>
    <br>
    <div class='reserve-info'>
    <p class='esup'>예매공연 : {{ post.show_title}}</p>
    <!--이부분 그냥 무식하게 다 썼는데 좋은 방법있으면 고쳐주세오...-->
    <p class='esup'>{% if ticket.t_choice == 'ticket1' %}
    예매티켓 : {{ ticket.post.ticket_date_1 }} <br>
    {% elif ticket.t_choice == 'ticket2' %} 
    예매티켓 : {{ ticket.post.ticket_date_2 }} <br>
    {% elif ticket.t_choice == 'ticket3' %}
    예매티켓 : {{ ticket.post.ticket_date_3 }} <br>
    {% elif ticket.t_choice == 'ticket4' %}
    예매티켓 : {{ ticket.post.ticket_date_4 }} <br>
    {% endif %}</p>
    <p class='esup'>매수 : {{ ticket.count }}</p>
    </div>
    <br>
    <br>
    <br>
    <button type='button' class='btn btn-warning complete-btn'><a class='complete-btn esup' href="{% url 'performance' index=post.pk %}">공연정보</a></button>
    
    <br>
    <br>
    <button type='button' class='btn btn-warning complete-btn'><a class='complete-btn esup' href="{% url 'c_mypage' %}">예매정보</a></button>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    

</div>




{% endblock %}

templates/blog/new_performance.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
{% load staticfiles %}
    <div class='container'>
    <div class='upper_blank'></div>
    <div class='upper_blank'></div>
    <h1 class="esup h1_center">새 공연 등록</h1>

     <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ form.as_p}} -->
        
        <div class='upper_blank'></div>
        <div class='basic-info'>
            <center>
                <h3 class='esup h3_center'>기본 정보</h3>
            </center>
        </div>
        <p>
            <div class='form-group'>
                <label for="id_show_title" class='esup'>공연/전시명: <span class="required">*</span></label>
                <input type="text" name="show_title" class="form-control" maxlength="200" id="id_show_title" placeholder='OO동아리 n차 정기공연' required >
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_show_poster" class='esup'>포스터:</label>
                <input type="file" class='form-control-file' name="show_poster" accept="image/*" id="id_show_poster">
            </div>
        </p>

        <p>
            <div class='form-group'>
                <label for="id_show_start_date" class='esup'>공연 시작 날짜:<span class="required">*</span</label>
                <input type="date" class='form-control' name="show_start_date" id="id_show_start_date" placeholder='2019-01-20' required>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_show_end_date" class='esup'>공연 마감 날짜:<span class="required">*</span</label>
                <input type="date" class='form-control' name="show_end_date" id="id_show_end_date" placeholder='2019-01-20' required>
            </div>
        </p>

        <p>
            <div class='form-group'>
                <label for="id_show_time" class='esup'>관람 시간: <span class="required">*</span></label>
                <textarea name="show_time" cols="40" rows="10" id="id_show_time" class='form-control' placeholder='월요일: 6시 ~ 7시 30분&#13;&#10;수요일: 7시 ~ 8시 반&#13;&#10;금요일: 6시 ~ 7시 30분' required></textarea>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_show_place" class='esup'>장소: <span class="required">*</span></label>
                <textarea name="show_place" cols="40" rows="10" id="id_show_place" class='form-control' placeholder='주소형식으로 써주세요. 예)서울특별시 마포구 백범로 35 (신수동) 서강대학교 메리홀(M관)'required></textarea>
            </div>
        </p>

        <!--model에서 show_info_text에 blank=True를 넣어줘야 함-->
        <p>
            <div class='form-group'>
                <label for="id_show_info_text" class='esup'>공연 설명/안내사항 (텍스트):</label>
                <textarea name="show_info_text" class='form-control' cols="40" rows="10" id="id_show_info_text"></textarea>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_show_info_image" class='esup'>공연 설명/안내사항 (이미지):</label>
                <input type="file" name="show_info_image" class='form-control-file' accept="image/*" id="id_show_info_image">
            </div>
        </p>


        <div class='upper_blank'></div>
        <div class='ticket-info'>
            <center>
                <h3 class='esup h3_center'>티켓 정보</h3>
            </center>
        </div>


        <p>
            <div class='form-group'>
                <label for="id_ticket_date_1" class='esup'>공연/전시 날짜: <span class="required">*</span></label>
                <div class='ticket' id="ticket">
                    <!--<input type="text" name="ticket_date_1" cols="40" rows="10" id="id_ticket_date_1" class='form-control' placeholder="날짜별로 티켓을 만들어 드립니다. 공연이나 전시를 진행하는 날짜를 입력해주세요. 예)2019-1-20, 2019-1-21, 2019-1-22, 2019-1-23" required>-->
                </div>
            </div>
        </p>

        
<script>
    var count = 1;
    var countArray = new Array;
    if(count<5) {
        countArray.length=5-count;
        for(var j=count, i=0 ; j<=4, i<5-count; j++, i++){
            countArray[i] = j;
        }
    }
    function addKeywordForm(){
     
        var addedFormDiv = document.getElementById("ticket");
     //   var addedFormDiv2 = document.getElementById("price");
        var nowcount = ($("div[id^='keyword_Frm']").length+1);
        
        var str = '<input type="date" name="ticket_date_' + countArray[0] + '" cols="40" rows="10" id="id_ticket_date_'+countArray[0] + 
        '" class="form-control" placeholder="날짜별로 티켓을 만들어 드립니다. 공연이나 전시를 진행하는 날짜를 입력해주세요.">' 
        +'<br>' + '<div class="flex">' +
        '<input type="number" name="ticket_price_' + countArray[0] 
        + '" class="form-control" min="-9223372036854775808" max="9223372036854775807" id="id_ticket_price_' + countArray[0]
        + '" placeholder="3000" style="width:300px;"> <span class="esup won">원</span>' + '</div>' + '<br>' + '<div class="flex">' +
        ' <input type="number" name="ticket_amount_' + countArray[0]
        + '" class="form-control" min="-9223372036854775808" max="9223372036854775807" id="id_ticket_amount_' + countArray[0]
        + '" placeholder="1000" style="width:300px;"> <span class="esup amount">개</span>' +'</div>' +'<br>' + '<input type="button" class="btn btn-danger" name ="del_ticket" value="삭제" onclick="delKeywordForm('+countArray[0]+');">' +'<br>' + '<br>'

        if(nowcount<=4){
            var addedDiv = document.createElement("div");
            addedDiv.setAttribute("id", "keyword_Frm"+countArray[0]);
            addedDiv.innerHTML = str;
            addedFormDiv.appendChild(addedDiv);
        //    addedDiv.innerHTML = str2;
         //   addedFormDiv2.appendChild(addedDiv);
            countArray.shift();
        }
        else{
            alert("티켓은 4개까지 입력하실 수 있습니다.")
        }
    }
    function delKeywordForm(thisCount){
        var addedFormDiv = document.getElementById("ticket");
      //  var addedFormDiv2 = document.getElementById("price");
        var nowcount = $("div[id^=keyword_Frm]").length;
        if(nowcount>=1){
            var thisDiv = document.getElementById("keyword_Frm" + thisCount);
            addedFormDiv.removeChild(thisDiv);
       //     addedFormDiv2.removeChild(thisDiv);
            countArray.push(thisCount);

        }
        else{
            document.addedFormDiv.reset();
         //   document.addedFormDiv2.reset();
            
        }
    }
</script> 
    <input type="button" class="btn btn-warning" name="add_ticket" value="추가" onclick="addKeywordForm();"> 
        <!-- <p>
            <div class='form-group'>
                <label for="id_ticket_price" class='esup'>티켓 가격: <span class="required">*</span></label>
                <div class='flex' id="price">
                    ##<input type="number" name="ticket_price" class='form-control' min="-9223372036854775808" max="9223372036854775807" id="id_ticket_price" placeholder='3000' required>
                    ##<span class='esup won'>원</span>
                </div>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_ticket_amount" class='esup'>티켓 수량:<span class="required">*</span></label>
                <div class='flex'>
                    ##<input type="number" name="ticket_amount" class='form-control' min="-9223372036854775808" max="9223372036854775807"  id="id_ticket_amount" placeholder="1000" required>
                    ##<span class='esup amount'>개</span>
                </div>
            </div>
        </p> -->


        <p>
            <div class='form-group'>
                <label for="id_bankname" class='esup'>입금 계좌 은행:<span class="required">*</span></label>
                <input type="text" name="bankname" maxlength="200" class='form-control' placeholder='국민' id="id_bankname" required>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_account" class='esup'>입금 계좌:<span class="required">*</span></label>
                <input type="number" name="account" min="-9223372036854775808" max="9223372036854775807" class='form-control' id="id_account" placeholder='하이픈(-)없이 입력해주세요 예)12345601123456' required>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_opendate" class='esup'>티켓 판매 시작일:</label>
                <input type="date" class='form-control' name="opendate" id="id_opendate" placeholder='2019-1-15'>
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_closedate" class='esup'>티켓 판매 마감일: </label>
                <input type="date" class='form-control' name="closedate" id="id_closedate" placeholder="2019-1-19">
            </div>
        </p>
        <p>
            <div class='form-group'>
                <label for="id_canceldate" class='esup'>티켓 취소 마감일:
                </label>
                <input type="date" class='form-control' name="canceldate" id="id_canceldate" placeholder='2019-1-20'>
            </div>
        </p>
        
        <div class='upper_blank'></div>
        <div class='btn_container'>
            <button class='register_button' type="submit">
                <img class='btn_register' src="{% static 'images/btn_upload.png' alt='btn upload fail' %}">
            </button>
        </div>  
    </form> 

    </div>
{% endblock %}

templates/blog/pay.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
{% load staticfiles %}

{% if user.is_authenticated and user.cuser.check %}
<div class='container'>
    <div class='upper_blank'></div>
    <div class='upper_blank'></div>
    <div class='upper_blank'></div>
    <div class='upper_blank'></div>

    <center><h3 class='esup h3_center_pay'>예매하기</h3></center>
    <br>
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            <p class='esup'><label for="id_t_choice">티켓 선택하기:</label>
            <select name="t_choice" class="form-control" id="id_t_choice">
                <option value="ticket1">{{ post.ticket_date_1 }}</option>
                <option value="ticket2">{{ post.ticket_date_2 }}</option>
                <option value="ticket3">{{ post.ticket_date_3 }}</option>
                <option value="ticket4">{{ post.ticket_date_4 }}</option>
            </select></p>
        </div>
        

        <p class='esup'><label for="id_count">티켓 매수:</label><input class='form-control' type="number" name="count" value="1" required id="id_count"></p>
        <div class='btn_container'>
        <button class='register_button' type="submit">
            <img class='btn_register' src="{% static 'images/btn_confirm.png' alt='btn upload fail' %}">
        </button>
        </div>
    </form>
</div>
{% else %}
<h3>공연자회원은 예매할 수 없습니다.</h3>
{% endif %}

{% endblock %}

templates/blog/performance.html
<!DOCTYPE html>
{% extends 'base/navbar.html' %}

{% block content %}
{% load staticfiles %}
    <head>
        <link rel="stylesheet" href="{% static 'css/blog_style.css' %}">
    </head>
    <body class="esup" id="unflex">
        {% if post.show_poster %}
        <div class="poster_img">
            <img src="{{post.show_poster.url}}"> 
        </div>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        {% endif %} 
        <br>

        <p>좋아요 : {{ post.postlike_set.count }}개</p>
            <a class="btn btn-info" href="{% url 'like' pk=post.pk %}">좋아요</a>  
         
        <div class="post">
            <br>
            <div id="sec">
                <p id="post_title"> {{ post.show_title }}</p>
                <hr>
                <p id="post_mintitle">기본 정보</p>
                <hr>
                <table id="sec_table">
                    <tr>
                        <th>공연 단체</th><td>&nbsp;&nbsp;&nbsp;{{post.post_author}}</td>
                    </tr>
                    <tr>
                        <th>공연 날짜</th><td>&nbsp;&nbsp;&nbsp;{{post.show_date}}</td>
                    </tr>
                    <tr>
                        <th>공연 시간</th><td>&nbsp;&nbsp;&nbsp;{{post.show_time}}</td>
                    </tr>
                    <tr>
                        <th>공연 장소</th><td>&nbsp;&nbsp;&nbsp;{{post.show_place}}</td>
                    </tr>
                </table>
            </div>
            <br>
            <div id="sec">
                <p id="post_mintitle">가격 정보</p>
                <hr>
                <table id="sec_table">
                    <tr>
                        <th>티켓 가격</th><td>&nbsp;&nbsp;{{post.ticket_price}}</td>
                    </tr>
                    <tr>
                        <th>티켓 개수</th><td>&nbsp;&nbsp;{{post.ticket_amount}}</td>
                    </tr>
                    <tr>
                        <th>계좌 정보</th><td>&nbsp;&nbsp;{{post.bankname}} {{post.account}}</td>
                    </tr>
                </table>
                <!-- <p id="post_content"> 티켓 날짜 : {{post.ticket_date}}</p> -->
            </div>
            <br>
            <div id="sec">
                <p id="post_mintitle">판매 기간 정보</p>
                <hr>
                <table id="sec_table">
                    <tr>
                        <th>판매 시작일</th><td>&nbsp;&nbsp;&nbsp;{{post.opendate}}</td>
                    </tr>
                    <tr>
                        <th>판매 종료일</th><td>&nbsp;&nbsp;&nbsp;{{post.closedate}}</td>
                    </tr>
                    <tr>
                        <th>취소 마감일</th><td>&nbsp;&nbsp;&nbsp;{{post.canceldate}}</td>
                    </tr>
                </table>
            </div>
            <br>
            <div id="sec">
                <p id="post_mintitle">공연 상세 정보</p>
                <hr>
                <p id="post_content"> {{post.show_info_text}}</p>
                {% if post.show_info_image %}
                <img src="{{post.show_info_image.url}}" width="100%">
                {% endif %}
            </div>
            <br>
            <div id="sec">
                    <p id="post_subtitle">공연 댓글(기대평/후기)</p>
                    {% for comment in comments %}
                        <div>
                            <p id="comment" style="color: #a3a3a3">{{comment.author}}, {{comment.timestamp}}</p>
                            <p id="comment">{{comment.content}}</p>
                            <hr>
                        </div>
                    {% endfor %}
                    <br>
                <div id="last_sec">
                    <form method="POST">
                        {% csrf_token %}
                        <p>
                        {% if user.cuser.check %} <!--예매자회원에게만-->
                            <div class='form-group'>
                                <label id="post_content" for="id_content" class='esup'>후기를 남겨주세요. </label> <br>
                                &nbsp;<textarea id="comment" name="content" cols="74" maxlength="300" required="" id="id_content"></textarea><br>
                                &nbsp;<input class="btn btn-outline-dark"  id="comment" type="submit" value="댓글 작성">
                            </div>
                            <!--
                                <form action="" method ="post">{% csrf_token %}
                                    <input type="submit" value="삭제하기">
                                </form>
                            -->
                        {% endif %}
                        </p>
                    </form>
                </div>
            </div>
            <br>
        </div>
        <br> <br> <br>
        <!--예매자회원에게만 뜨게-->
        {% if user.is_authenticated and user.cuser.check %}
        <button type="button" id="book-btn" class="btn btn-block"><a href="{% url 'pay' index=post.pk %}" id="link_color">예매하기</a></button>
        {% endif %}
        
    </body>
{% endblock %}